// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorTheme = "waku_light" | "waku_dark" | "catppuccin_latte" | "catppuccin_frappe" | "catppuccin_macchiato" | "catppuccin_mocha" | "tokyo_night" | "tokyo_storm" | "tokyo_moon" | "tokyo_day" | "rose_pine" | "rose_pine_moon" | "rose_pine_dawn" | "gruvbox_dark" | "gruvbox_light" | "vesper" | "kanagawa_wave" | "kanagawa_lotus" | "nord" | "dracula" | "one_dark" | "solarized_dark" | "solarized_light" | "everforest_dark" | "everforest_light";
